title: FirstVision API Documentation
show_downloads: false
#theme: jekyll-theme-cayman
github:
  is_project_page: false
navigation:
  name_over_title: true
  strip_par: true
  sanitize: true
  h_max: 3