################################################################################
# Copyrights © 2021-2022 Fiserv, Inc. or its affiliates.
# Fiserv is a trademark of Fiserv, Inc.,
# registered or used in the United States and foreign countries,
# and may or may not be registered in your country.
# All trademarks, service marks,
# and trade names referenced in this
# material are the property of their
# respective owners. This work, including its contents
# and programming, is confidential and its use
# is strictly limited. This work is furnished only
# for use by duly authorized licensees of Fiserv, Inc.
# or its affiliates, and their designated agents
# or employees responsible for installation or
# operation of the products. Any other use,
# duplication, or dissemination without the
# prior written consent of Fiserv, Inc.
# or its affiliates is strictly prohibited.
# Except as specified by the agreement under
# which the materials are furnished, Fiserv, Inc.
# and its affiliates do not accept any liabilities
# with respect to the information contained herein
# and are not responsible for any direct, indirect,
# special, consequential or exemplary damages
# resulting from the use of this information.
# No warranties, either express or implied,
# are granted or extended by this work or
# the delivery of this work
################################################################################

header:
  productionDescription: FirstVision is our outsourced processing solution that meets your challenges head-on and transforms your technology capability. Built on core VisionPLUS® software, FirstVision™ provides an end-to-end solution that delivers global processing economies of scale plus fully integrated adjacent services that span the issuing lifecycle.
getStarted: /docs/Introduction.md
benefits:
  - title: Accelerating Your Time to Market
    description: Extensive parameterisation and service-based architecture with API enabled and a fully integrated suite of solutions for managing credit, debit, loans and payments ensures quicker application development and integration, rapid roll-out of new products and services.
  - title: Helping You Ride the Latest Wave of Innovation
    description: Platform architecture built around technology simplification and leveraging open APIs, reducing the cost of change and meeting your need for ongoing innovation to differentiate your product set – now and forward into the future.
  - title: Enables Rapid Speed to Market
    description: FirstVision™ oriented architecture with open APIs enables service consumption rather than change management.
guides:
  - title: Fiserv API connectivity
    description: Fiserv API connectivity guide on necessary steps required to set up an existing or new client to access the API. The process is common for accessing APIs in EMEA and APAC region
    link: docs/Support/Client-Onboarding.md
  - title: APIs over internet channel
    description: This guide will provide you with registration and token generation process to access APIs over internet channel.
    link: docs/Support/Registration-and-Token.md
featuredFeatures:
  - title: Customer
    featured: true
    description: The customer use cases relate to the information kept at the customer level. This is mainly demographic information.
    relatedDocs:
      - link: docs/Self-servicing/Customer/customer.md
        title: Customer
  - title: Account
    featured: true
    description: In the account section, you will find use cases relating the a customer's account. This will hold all the financial information, such as balances, spend limits, and transactions.
    relatedDocs:
      - link: docs/Self-servicing/Account/account.md
        title: Account
  - title: Card
    featured: true
    description:  The customer use cases relate to the information kept at the customer level. This is mainly demographic information.
    relatedDocs:
      - link: docs/Self-servicing/Card/Card.md
        title: Card
  - title: Retrieve customer number
    groupName: Customer
    description: Use the account number or the card number to retrieve the customer number and alternate customer number, if applicable.
    relatedDocs:
      - link: docs/Self-servicing/Customer/Retrieve-customer-number.md
        title: Retrieve customer number
    relatedAPIs:
      - type: post
        path: /fv_emea/v3/accountDetailInquiry
        title: Account Detail Inquiry
  - title: Update customer demographics
    groupName: Customer
    description: Update customer demographics, such as name, address, phone and email.
    relatedDocs:
      - link: docs/Self-servicing/Customer/Update-customer-demographics.md
        title: Update customer demographics
    relatedAPIs:
      - type: post
        path: /fv_emea/v2/customerDataUpdate
        title: Customer Data Update
  - title: Update customer user fields
    groupName: Customer
    description: Update user fields on the Customer record.
    relatedDocs:
      - link: docs/Self-servicing/Customer/Update-customer-user-fields.md
        title: Update customer user fields
    relatedAPIs:
      - type: post
        path: /fv_emea/v2/customerDataUpdate
        title: Customer Data Update
  - title: Retrieve customer contact preferences
    groupName: Customer
    description: Retrieve a customer's contact preference settings.
    relatedDocs:
      - link: docs/Self-servicing/Customer/Retrieve-customer-contact-preferences.md
        title: Retrieve customer contact preferences
    relatedAPIs:
      - type: post
        path: /fv_emea/v1/customerDemographicInquiry
        title: Customer Demographic Inquiry
  - title: Update contact preferences
    groupName: Customer
    description: Update contact preferences on the Customer record.
    relatedDocs:
      - link: docs/Self-servicing/Customer/Update-contact-preferences.md
        title: Update contact preferences
    relatedAPIs:
      - type: post
        path: /fv_emea/v2/customerDataUpdate
        title: Customer Data Update
  - title: Open a new account
    groupName: Account
    description: Open a new account. This message will generate the account, as well as the associated primary customer and card records.
    relatedDocs:
      - link: docs/Self-servicing/Account/Open-a-new-account.md
        title: Open a new account
    relatedAPIs:
      - type: post
        path: /fv_emea/v1/customerAccountCardAdd
        title: Customer Account Card Add
  - title: Retrieve account number using customer number
    groupName: Account
    description: Retrieve all account numbers belonging to a customer.
    relatedDocs:
      - link: docs/Self-servicing/Account/Retrieve-account-number-using-customer-number.md
        title: Retrieve account number using customer number
    relatedAPIs:
      - type: post
        path: /fv_emea/v1/customerAccountsList
        title: Customer Accounts List
  - title: Retrieve account balance information
    groupName: Account
    description: Retrieve balance information for any account belonging to an existing customer.
    relatedDocs:
      - link: docs/Self-servicing/Account/Retrieve-account-balance-information.md
        title: Retrieve account balance information
    relatedAPIs:
      - type: post
        path: /fv_emea/v3/accountDetailInquiry
        title: Account Detail Inquiry
  - title: Retrieve account limits
    groupName: Account
    description: Retrieve financial limits for an account, including credit limits and spend limits.
    relatedDocs:
      - link: docs/Self-servicing/Account/Retrieve-account-limits.md
        title: Retrieve account limits
    relatedAPIs:
      - type: post
        path: /fv_emea/v3/accountDetailInquiry
        title: Account Detail Inquiry
  - title: Retrieve payment information
    groupName: Account
    description: Retrieve information relevant to the payments of the account, including dates when payments are due as well as amounts.
    relatedDocs:
      - link: docs/Self-servicing/Account/Retrieve-payment-information.md
        title: Retrieve payment information
    relatedAPIs:
      - type: post
        path: /fv_emea/v3/accountDetailInquiry
        title: Account Detail Inquiry
  - title: Retrieve plan information(interest and balance at plan level)
    groupName: Account
    description: Retrieve interest rate information for purchases, cash as well as promotional rates applicable to the account. In addition, this use case also returns balance information.
    relatedDocs:
      - link: docs/Self-servicing/Account/Retrieve-plan-information.md
        title: Retrieve plan information
    relatedAPIs:
      - type: post
        path: /fv_emea/v1/accountPlanInquiry
        title: Account Plan Inquiry
  - title: Retrieve transaction information
    groupName: Account
    description: Request 1- Retrieve all the transactions that have cleared on the account since the last statement cycle. Request 2- Retrieve transactions between two input dates.
    relatedDocs:
      - link: docs/Self-servicing/Account/Retrieve-transaction-information.md
        title: Retrieve transaction information
    relatedAPIs:
      - type: post
        path: /fv_emea/v4/transactionInquiry
        title: Transaction Inquiry
  - title: Retrieve direct debit information
    groupName: Account
    description: Retrieve information relating to the Direct Debit information of an account, including bank account details and status.
    relatedDocs:
      - link: docs/Self-servicing/Account/Retrieve-direct-debit-information.md
        title: Retrieve direct debit information
    relatedAPIs:
      - type: post
        path: /fv_emea/v1/directDebitInquiry
        title: Direct Debit Inquiry
  - title: Update credit limit of account
    groupName: Account
    description:  Here is how to update the total credit limit of the account. This applies to the overall limit on the account and not individual spend limits.
    relatedDocs:
      - link: docs/Self-servicing/Account/Update-credit-limit-of-account.md
        title: Update credit limit of account
    relatedAPIs:
      - type: post
        path: /fv_emea/v1/creditLimitUpdate
        title: Credit Limit Update
  - title: Update direct debit details
    groupName: Account
    description: Update information relating to the Direct Debit information of an account, including bank account details.
    relatedDocs:
      - link: docs/Self-servicing/Account/Update-direct-debit-details.md
        title: Update customer demographics
    relatedAPIs:
      - type: post
        path: /fv_emea/v2/directDebitUpdate
        title: Direct Debit Update
  - title: Retrieve card information
    groupName: Card
    description: Retrieve details of all cards (up to a maximum of 20) linked to an account such as card number, embossed name, expiry date on the card etc.
    relatedDocs:
      - link: docs/Self-servicing/Card/Retrieve-card-information.md
        title: Retrieve card information
    relatedAPIs:
      - type: post
        path: /fv_emea/v1/cardsListByAccount
        title: Cards List By Account
  - title: Update name on card
    groupName: Card
    description: Update the embossed name on a card.
    relatedDocs:
      - link: docs/Self-servicing/Card/Update-name-on-card.md
        title: Update name on card
    relatedAPIs:
      - type: post
        path: /fv_emea/v1/cardUpdate
        title: CardUpdate
  - title: Request a replacement card
    groupName: Card
    description: Replace a damaged card. This can also be used for requesting a new plastic follow a name change.
    relatedDocs:
      - link: docs/Self-servicing/Card/Request-a-replacement-card.md
        title: Request a replacement card
    relatedAPIs:
      - type: post
        path: /fv_emea/v1/cardReplacement
        title: Card Replacement
  - title: Request a PIN reminder(through batch process)
    groupName: Card
    description: Send a PIN reminder through the batch process for an existing PIN using methods specified on the account, e.g. SMS, mail, etc.
    relatedDocs:
      - link: docs/Self-servicing/Card/Request-pin-reminder.md
        title: Request a PIN reminder
    relatedAPIs:
      - type: post
        path: /fv_emea/v1/pinReminder
        title: Pin Reminder
  - title: Block a card
    groupName: Card
    description: Apply a block code to an existing card in order to prevent spend on the card.
    relatedDocs:
      - link: docs/Self-servicing/Card/Block-a-card.md
        title: Block a card
    relatedAPIs:
      - type: post
        path: /fv_emea/v1/cardBlockCodeUpdate
        title: Card Block Code Update
  - title: Report a lost/stolen or fraudulent card
    groupName: Card
    description: Report a lost / stolen / fradulent activity on a  card and generate a new card and PIN.
    relatedDocs:
      - link: docs/Self-servicing/Card/Report-a-fraudulent-card.md
        title: Report a lost/stolen or fraudulent card
    relatedAPIs:
      - type: post
        path: /fv_emea/v2/lostStolenUpdate
        title: Lost Stolen Update
